language: android
jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra

after_failure:
    - cat app/build/reports/lint-results*.xml
