language: android
jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.1
    - android-28
    - extra

after_failure:
    - cat app/build/reports/lint-results*.xml
