language: android
jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-28"
  - sudo apt-get update
  - sudo apt-get install -y mono-runtime

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra

after_failure:
    - cat app/build/reports/lint-results*.xml
