language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra

after_failure:
    - cat app/build/outputs/lint-results*.xml
