language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra

after_failure:
    - cat app/build/reports/lint-results*.xml
